services:
  # Backend API Server
  - type: web
    name: symbiont-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: ALLOWED_ORIGINS
        value: "https://capycare.onrender.com"
      # Add your API keys as environment variables in Render dashboard
      - key: APP_ID
        sync: false  # Set manually in Render dashboard
      - key: APP_KEY
        sync: false  # Set manually in Render dashboard  
      - key: GEMINI_API_KEY
        sync: false  # Set manually in Render dashboard
    healthCheckPath: /health
    
  # Frontend React App
  - type: web  
    name: symbiont-frontend
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: "https://symbiont.onrender.com"
